services:
  - type: web
    name: leakosint-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: DATABASE_URL
        sync: false
