services:
  - type: web
    name: leakosint-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: SHODAN_API_KEY
        sync: false
      - key: HUNTER_API_KEY
        sync: false
      - key: HIBP_API_KEY
        sync: false
      - key: DEHASHED_EMAIL
        sync: false
      - key: DEHASHED_API_KEY
        sync: false
      - key: DATABASE_URL
        value: sqlite:///data/leakosint_bot.db
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
